### ISSUE TITLE
3.0.0 Release tracking

### ISSUE THREAD

**Issue by isabelle-dr** [MobilityData/gtfs-validator#1046]
This is an issue for the 3.0.0 release tracking. It was initially planned for the end beginning October 2021.
For the exhaustive list of everything included in this release, please refer to the [3.0.0 Milestone tag](https://github.com/MobilityData/gtfs-validator/milestone/4).
Update November 9, 2021: [the v3.0.0 is out in pre-release!](https://github.com/MobilityData/gtfs-validator/releases/tag/v3.0.0) 🎉
Update November 29, 2021: for the first time, we ran analytics on all the datasets available on the mobility database! Results [here](https://github.com/MobilityData/gtfs-validator/issues/1041).
Update January 10, 2022: the last PR is merged, which wraps up this release, better late than never! 

## Goals for the release 🎯
1. Solve discrepancies with the [official GTFS specification](https://github.com/google/transit/blob/master/gtfs/spec/en/reference.md). This has been done after the [update to RFC 2119](https://github.com/google/transit/issues/273)  has been done. The V2.0.0 to V3.0.0 rule mapping is available [here](https://bit.ly/validator_rule_mapping).
2. Implement automated tests to see if a Pull Request would result in datasets from the [mobility database](http://mobilitydatabase.org/wiki/Main_Page) getting additional errors.
3. Make sure MobilityData's work has related public communication to facilitate community contribution (issues opened, public sprint board and bug tracking board, roadmap, ways for users to voice what they'd like to see next and for contributors to see how to get involved).

### 1. Solve discrepancies with the spec

- https://github.com/MobilityData/gtfs-validator/issues/920 
  - https://github.com/MobilityData/gtfs-validator/pull/929
- https://github.com/MobilityData/gtfs-validator/issues/909
  - https://github.com/MobilityData/gtfs-validator/pull/932)
- https://github.com/MobilityData/gtfs-validator/issues/907 
  - https://github.com/MobilityData/gtfs-validator/pull/932
  
**stops.txt**
- https://github.com/MobilityData/gtfs-validator/pull/500
- https://github.com/MobilityData/gtfs-validator/issues/910
  - https://github.com/MobilityData/gtfs-validator/pull/937
- https://github.com/MobilityData/gtfs-validator/issues/237
  - https://github.com/MobilityData/gtfs-validator/pull/936
- https://github.com/MobilityData/gtfs-validator/pull/1068

**stop_times.txt**
- https://github.com/MobilityData/gtfs-validator/issues/763
  - https://github.com/MobilityData/gtfs-validator/pull/938

**pathways.txt**
- https://github.com/MobilityData/gtfs-validator/issues/980
  - https://github.com/MobilityData/gtfs-validator/pull/961
  - https://github.com/MobilityData/gtfs-validator/pull/999
- https://github.com/MobilityData/gtfs-validator/issues/975
  - https://github.com/MobilityData/gtfs-validator/pull/997
- https://github.com/MobilityData/gtfs-validator/issues/974
  - https://github.com/MobilityData/gtfs-validator/pull/998

**translations.txt**
- https://github.com/MobilityData/gtfs-validator/issues/820
  - https://github.com/MobilityData/gtfs-validator/pull/968

**levels.txt**
- https://github.com/MobilityData/gtfs-validator/issues/921
  - https://github.com/MobilityData/gtfs-validator/pull/967
  - https://github.com/MobilityData/gtfs-validator/pull/966
  - https://github.com/MobilityData/gtfs-validator/pull/969

### 2. Automated test to see if a PR results in additional errors
- https://github.com/MobilityData/gtfs-validator/issues/1045
  - https://github.com/MobilityData/gtfs-validator/pull/1037
  - https://github.com/MobilityData/gtfs-validator/pull/1038
  - https://github.com/MobilityData/gtfs-validator/pull/926
  - https://github.com/MobilityData/gtfs-validator/pull/848

### 3. Public communication

- [x] Public sprint board
- [x] Publig bug tracking board, populated automatically
- [x] Public Release plan / release tracking issue (this one!)
- [x] High level Roadmap in a ProductBoard portal (link coming shortly)

## Other work included
**Better rules**
- https://github.com/MobilityData/gtfs-validator/pull/956
- https://github.com/MobilityData/gtfs-validator/pull/944
- https://github.com/MobilityData/gtfs-validator/pull/958
- https://github.com/MobilityData/gtfs-validator/pull/957

**Better user experience**
- https://github.com/MobilityData/gtfs-validator/issues/899
  - https://github.com/MobilityData/gtfs-validator/pull/925
  - https://github.com/MobilityData/gtfs-validator/pull/951
  - https://github.com/MobilityData/gtfs-validator/pull/952
- https://github.com/MobilityData/gtfs-validator/issues/539
  - https://github.com/MobilityData/gtfs-validator/pull/851
- https://github.com/MobilityData/gtfs-validator/issues/838
  - https://github.com/MobilityData/gtfs-validator/pull/901
- https://github.com/MobilityData/gtfs-validator/issues/857
  - https://github.com/MobilityData/gtfs-validator/pull/888

**Bugs**
- https://github.com/MobilityData/gtfs-validator/issues/959
- https://github.com/MobilityData/gtfs-validator/issues/954
- https://github.com/MobilityData/gtfs-validator/issues/1010
- https://github.com/MobilityData/gtfs-validator/pull/1062

**Other good stuff**
- https://github.com/MobilityData/gtfs-validator/pull/1014
- https://github.com/MobilityData/gtfs-validator/pull/953
- https://github.com/MobilityData/gtfs-validator/pull/965
............... and much more 

## Contributors 🙏
**Massive shoutout to:**
🎉 @lionel-nj 
🎉 @maximearmstrong 
🎉 @barbeau 
🎉 @aababilov 
🎉 @asvechnikov2

**Comment by isabelle-dr** [comment]
Update November 9, 2021: [the v3.0.0-beta is out!](https://github.com/MobilityData/gtfs-validator/releases/tag/v3.0.0-beta) 🎉

**Comment by markstos** [comment]
I tried the 3.0 beta. It worked pretty well, but declared a phone number in the phone number 111-222-333 as invalid, although according to the spec, it seems like should be valid:

https://developers.google.com/transit/gtfs/reference#agencytxt

I believe this issue may already be fixed now by: https://github.com/MobilityData/gtfs-validator/pull/1062 but is not included in the beta release.

**Comment by isabelle-dr** [comment]
Hi @markstos , the issue has been fixed, you can use [this jar file](https://github.com/MobilityData/gtfs-validator/suites/4467368246/artifacts/118793764) to run the version of the validator where this issue is fixed!

**Comment by isabelle-dr** [comment]
The [last PR](https://github.com/MobilityData/gtfs-validator/pull/848) is now merged, closing this issue
