### ISSUE TITLE
Web Validator: add Cypress testing to web client

### ISSUE THREAD

**Issue by themightychris** [MobilityData/gtfs-validator#1390]
@mijogu

We want a Cypress project scaffolded and integrated with GitHub Actions for the [Svelte](https://svelte.dev/)-based web frontend under `web/client` within this repo. The Cypress project should include one end-to-end test for the core user workflow and several [component tests](https://docs.cypress.io/guides/component-testing/svelte/overview) for the most complicated Svelte components (`.svelte` files under `src/lib` and `src/routes`)

## Roadmap

- [x] Scaffold Cypress project
    - Configure the online validator instance as the default baseUrl
- ~[ ] Set up Cypress' [Svelte integration](https://docs.cypress.io/guides/component-testing/svelte/quickstart)~
- [x] Create one end-to-end test against live web service
    1. Navigate to baseUrl
    2. Input `https://developers.google.com/static/transit/gtfs/examples/sample-feed.zip` as URL
    3. Click Validate
    4. Intercept POST to `/create-job`, wait for it and assert it runs exactly once and succeeds and returns a `{ jobId: '...' }` data structure with a nonempty `jobId`
    5. Intercept HEAD to `/${jobId}/report.html` and wait for that to happen at least once with a response status of 200 OR 404
    6. With an extended timeout, wait for the "Your report is ready!" modal to appear and verify that the link is to your `${jobId}/report.html`
- [x] Update end-to-end test to use mock API responses and not hit the real web service at all
    1. Mock the `POST .../create-job` request to return a hard-coded `jobId`
    2. Mock the `HEAD .../${jobId}/report.html` request to respond 404 2 times and then 200 on the 3rd request
    3. Adjust the wait for `/${jobId}/report.html` to have 3 hardcoded waits in serial where each asserts the correct count of calls and the return status being 404, 404, and then 200
    4. Drop the timeout on the "Your report is ready!" modal UI appearing to assert that it is displaying nearly immediately after the 3rd and final wait for `report.html` to return 200
- ~[ ] Review `.svelte` components and identify the 3-6 most complex ones to develop component tests for that try out different input parameters and assert on key UI elements that should reflect those inputs~
- [x] Add a new GitHub Actions workflow that runs [the action provided by the Cypress project](https://github.com/cypress-io/github-action)
    - Have it triggered by all pull requests against `master` like the [acceptance_test workflow](https://github.com/MobilityData/gtfs-validator/blob/master/.github/workflows/acceptance_test.yml) is
    - Rather than using `paths-ignore` like other workflows triggered by `pull_request` events, this workflow can just use the [`paths` filter](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet) on `web/client/**`
- [x] Add E2E test cases to trigger error displays added in #1383

**Comment by themightychris** [comment]
We've de-scoped implementing frontend unit/component testing at this time. We ran into Cypress's svelte support not including svelte*kit* support yet, which is pending: https://github.com/cypress-io/cypress/issues/23618

A workaround [here](https://github.com/cypress-io/cypress/issues/26064#issuecomment-1475437226) proved sufficient to get it working in the short-term. Alternatively we looked at the whole [Vitest](https://vitest.dev/) unit testing framework we could set up that SvelteKit recommends.

Looking closer though at what's actually available to component/unit test right now... the UI components we have in place have very little complexity that can be tested in isolation. Given the current state of the frontend, we felt that a better investment of time would be extending the e2e testing to cover server error cases. That's where more of the frontend complexity is and we can exercise it by mocking server responses which are already in place. If we have more complex UI components in the future, hopefully Cypress' first-class will be ready. At this point even with a unit/component testing in place and properly integrated with SvelteKit we'd be building more complexity in the tests to isolate each component than the components contain.

**Comment by davidgamez** [comment]
I'm OK with the general approach of adding more e2e to cover edges. I wouldn't add a lot of them to cover every single case, e2e tends to be slower and catch fewer errors than unit tests.
For future work on unit testing, I recommend going with a simple path. We can extract the functions from the svelte files and separate the presentation components from the logic. With this, we can use `jest` and `mocking` for testing functions in isolation and not depending on an extra framework to cover most of the cases.

**Comment by themightychris** [comment]
> We can extract the functions from the svelte files and separate the presentation components from the logic.

That's the thing, there just really is no worthwhile UI logic at this point... we looked through all the components to find a good one to test and most have no logic at all, and some have at most flat single-variable render branching. I agree with you in general, but this particular project at this point in time is a very dumb thin-client and its only job is to catch network status and successfully propagate it down to the needed display components. There's no evolving state, there's no logic beyond render switching... the most/only complex thing that could fail is a break in the chain from catching network status to passing status all the way down the component tree to the components that display errors. The e2e suite has network response mocking in place and can exercise the failed response -> display chain in milliseconds.

If this codebase expands into rendering interactive reports down the line, it could make sense at that point to level up the testing regimen. With its current scope of responsibility though, it's hard to imagine it gaining any UI complexity worth setting up isolated tests for. The balance of the maintenance burden and brittleness of the testing infrastructure vs the target code being tested would be uneconomical until this frontend has a bigger job.
